# Generated by Django 3.1.7 on 2021-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(blank=True, default='DEFAULT VALUE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
