# Generated by Django 3.1.7 on 2021-04-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20210422_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(upload_to='Jobseeker'),
        ),
    ]
