# Generated by Django 3.1.7 on 2021-04-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20210423_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
